run:
  timeout: 5m

issues:
  include:
    # Disable excluding of issues about comments from revive. This enables the
    # warning that each exported var/const/struct/function/method should have
    # a Godoc. It is disabled nby default via `exclude-use-default` which
    # defaults to true.
    - EXC0012

linters:
  # We run with all default linters enabled and in addition the linters
  # listed below.
  enable:
    - bodyclose
    - exportloopref
    - goimports
    - gosec
    - makezero
    - revive
    - unconvert
    - wastedassign

linters-settings:
  goimports:
    local-prefixes: github.com/astrocode-id/go-flaresolverr
