version: 2.1
parameters:
  golangci-lint-version:
    type: string
    default: "v1.50.1"

  golang-version:
    type: string
    default: "1.19"

jobs:
  test:
    docker:
      - image: cimg/go:<< pipeline.parameters.golang-version >>

    steps:
      - checkout
      - run:
          name: Run tests (-race)
          command: go test -race ./...

  checks:
    docker:
      - image: cimg/go:<< pipeline.parameters.golang-version >>

    steps:
      - checkout

      - restore_cache:
          key: golangci-lint-<< pipeline.parameters.golangci-lint-version >>

      - run:
          name: Install golangci-lint
          command: |
            BIN_DIR=$(go env GOPATH)/bin

            if [ ! -f "${BIN_DIR}/golangci-lint" ]; then
                echo "golangci-lint << pipeline.parameters.golangci-lint-version >> not installed yet"
                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ${BIN_DIR} << pipeline.parameters.golangci-lint-version >>
            fi

      - save_cache:
          key: golangci-lint-<< pipeline.parameters.golangci-lint-version >>
          paths:
            - "/home/circleci/go/bin/golangci-lint"

      - run:
          name: Run golangci-lint
          no_output_timeout: 10m
          # See ../golangci.yml file for the configuration.
          command: |
            golangci-lint run ./...

workflows:
  version: 2
  test-checks:
    jobs:
      - test
      - checks
